use serde::{Deserialize, Serialize};
use serde_json::{Map, Value};

use crate::{DomainError, DomainResult, bucket::canonical_mime_type};

pub const CURRENT_METADATA_VERSION: u32 = 1;
pub const MAX_METADATA_BYTES: usize = 64 * 1024;
pub const MAX_METADATA_DEPTH: usize = 16;
pub const MAX_METADATA_KEYS: usize = 256;
pub const MAX_METADATA_STRING_BYTES: usize = 8 * 1024;

/// Media facts measured or generated by MediaHub, never accepted from a client
/// metadata request.
#[derive(Clone, Debug, PartialEq, Eq, Serialize)]
pub struct SystemMetadata {
    mime: String,
    size: u64,
    width: Option<u32>,
    height: Option<u32>,
    duration_ms: Option<u64>,
    sha256: String,
}

impl SystemMetadata {
    pub fn new(
        mime: impl AsRef<str>,
        size: u64,
        width: Option<u32>,
        height: Option<u32>,
        duration_ms: Option<u64>,
        sha256: impl Into<String>,
    ) -> DomainResult<Self> {
        let (width, height) = match (width, height) {
            (None, None) => (None, None),
            (Some(width), Some(height)) if width > 0 && height > 0 => (Some(width), Some(height)),
            _ => return Err(DomainError::InvalidMetadataShape),
        };
        let sha256 = sha256.into().to_ascii_lowercase();
        validate_sha256(&sha256)?;

        Ok(Self {
            mime: canonical_mime_type(mime.as_ref())?,
            size,
            width,
            height,
            duration_ms,
            sha256,
        })
    }

    #[must_use]
    pub fn mime(&self) -> &str {
        &self.mime
    }

    #[must_use]
    pub const fn size(&self) -> u64 {
        self.size
    }

    #[must_use]
    pub const fn width(&self) -> Option<u32> {
        self.width
    }

    #[must_use]
    pub const fn height(&self) -> Option<u32> {
        self.height
    }

    #[must_use]
    pub const fn duration_ms(&self) -> Option<u64> {
        self.duration_ms
    }

    #[must_use]
    pub fn sha256(&self) -> &str {
        &self.sha256
    }
}

/// Untrusted metadata accepted from clients. It intentionally has no `system`
/// field, and unknown namespaces are rejected during deserialization.
#[derive(Clone, Debug, Default, PartialEq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ClientMetadata {
    #[serde(default)]
    user: Map<String, Value>,
    #[serde(default)]
    ai: Map<String, Value>,
}

impl ClientMetadata {
    pub fn new(user: Map<String, Value>, ai: Map<String, Value>) -> DomainResult<Self> {
        let metadata = Self { user, ai };
        metadata.validate_content()?;
        Ok(metadata)
    }

    /// Parses the public metadata payload while preserving domain-specific error
    /// codes for rejected namespaces.
    pub fn from_value(value: Value) -> DomainResult<Self> {
        let Value::Object(mut namespaces) = value else {
            return Err(DomainError::InvalidMetadataShape);
        };

        if namespaces.contains_key("system") {
            return Err(DomainError::RestrictedMetadataNamespace);
        }

        for namespace in namespaces.keys() {
            if namespace != "user" && namespace != "ai" {
                return Err(DomainError::UnknownMetadataNamespace {
                    namespace: namespace.clone(),
                });
            }
        }

        let user = take_namespace(&mut namespaces, "user")?;
        let ai = take_namespace(&mut namespaces, "ai")?;
        Self::new(user, ai)
    }

    #[must_use]
    pub const fn user(&self) -> &Map<String, Value> {
        &self.user
    }

    #[must_use]
    pub const fn ai(&self) -> &Map<String, Value> {
        &self.ai
    }

    fn validate_content(&self) -> DomainResult<()> {
        validate_value(&Value::Object(self.user.clone()), 1, &mut 0)?;
        validate_value(&Value::Object(self.ai.clone()), 1, &mut 0)
    }
}

/// Persisted metadata combines MediaHub-generated facts with user-controlled
/// namespaces. The system namespace remains immutable after construction.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct MediaMetadata {
    system: SystemMetadata,
    user: Map<String, Value>,
    ai: Map<String, Value>,
}

impl MediaMetadata {
    pub fn new(system: SystemMetadata, client: ClientMetadata) -> DomainResult<Self> {
        let metadata = Self {
            system,
            user: client.user,
            ai: client.ai,
        };
        metadata.validate()?;
        Ok(metadata)
    }

    #[must_use]
    pub const fn system(&self) -> &SystemMetadata {
        &self.system
    }

    #[must_use]
    pub const fn user(&self) -> &Map<String, Value> {
        &self.user
    }

    #[must_use]
    pub const fn ai(&self) -> &Map<String, Value> {
        &self.ai
    }

    pub fn replace_client_metadata(&mut self, client: ClientMetadata) -> DomainResult<()> {
        let replacement = Self {
            system: self.system.clone(),
            user: client.user,
            ai: client.ai,
        };
        replacement.validate()?;
        *self = replacement;
        Ok(())
    }

    fn validate(&self) -> DomainResult<()> {
        validate_value(&Value::Object(self.user.clone()), 1, &mut 0)?;
        validate_value(&Value::Object(self.ai.clone()), 1, &mut 0)?;
        let serialized =
            serde_json::to_vec(self).expect("metadata is serializable by construction");
        if serialized.len() > MAX_METADATA_BYTES {
            return Err(DomainError::MetadataTooLarge {
                max_bytes: MAX_METADATA_BYTES,
            });
        }
        Ok(())
    }
}

fn take_namespace(
    namespaces: &mut Map<String, Value>,
    name: &str,
) -> DomainResult<Map<String, Value>> {
    match namespaces.remove(name) {
        None => Ok(Map::new()),
        Some(Value::Object(value)) => Ok(value),
        Some(_) => Err(DomainError::InvalidMetadataShape),
    }
}

fn validate_value(value: &Value, depth: usize, key_count: &mut usize) -> DomainResult<()> {
    if depth > MAX_METADATA_DEPTH {
        return Err(DomainError::MetadataTooDeep {
            max_depth: MAX_METADATA_DEPTH,
        });
    }

    match value {
        Value::String(value) => validate_string(value),
        Value::Array(values) => {
            for value in values {
                validate_value(value, depth + 1, key_count)?;
            }
            Ok(())
        }
        Value::Object(values) => {
            for (key, value) in values {
                validate_string(key)?;
                *key_count += 1;
                if *key_count > MAX_METADATA_KEYS {
                    return Err(DomainError::MetadataTooManyKeys {
                        max_keys: MAX_METADATA_KEYS,
                    });
                }
                validate_value(value, depth + 1, key_count)?;
            }
            Ok(())
        }
        Value::Null | Value::Bool(_) | Value::Number(_) => Ok(()),
    }
}

fn validate_string(value: &str) -> DomainResult<()> {
    if value.len() > MAX_METADATA_STRING_BYTES {
        return Err(DomainError::MetadataStringTooLong {
            max_bytes: MAX_METADATA_STRING_BYTES,
        });
    }
    Ok(())
}

fn validate_sha256(value: &str) -> DomainResult<()> {
    if value.len() != 64 || !value.bytes().all(|byte| byte.is_ascii_hexdigit()) {
        return Err(DomainError::InvalidSha256);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use serde_json::json;

    use super::*;

    fn system() -> SystemMetadata {
        SystemMetadata::new("image/png", 12, Some(2), Some(3), None, "a".repeat(64))
            .expect("valid system metadata")
    }

    #[test]
    fn client_metadata_cannot_supply_system_namespace() {
        assert_eq!(
            ClientMetadata::from_value(json!({"system": {"size": 1}})),
            Err(DomainError::RestrictedMetadataNamespace)
        );
        assert!(serde_json::from_value::<ClientMetadata>(json!({"system": {}})).is_err());
    }

    #[test]
    fn metadata_keeps_system_values_when_client_sections_are_replaced() {
        let original = ClientMetadata::from_value(json!({"user": {"project": "one"}}))
            .expect("valid client metadata");
        let mut metadata = MediaMetadata::new(system(), original).expect("valid media metadata");
        let replacement = ClientMetadata::from_value(json!({"ai": {"model": "gpt-image-2"}}))
            .expect("valid client metadata");

        metadata
            .replace_client_metadata(replacement)
            .expect("replacement is valid");

        assert_eq!(metadata.system().sha256(), "a".repeat(64));
        assert!(metadata.user().is_empty());
        assert_eq!(metadata.ai().get("model"), Some(&json!("gpt-image-2")));
    }

    #[test]
    fn metadata_limits_nested_data_and_strings() {
        let excessively_long = "x".repeat(MAX_METADATA_STRING_BYTES + 1);
        assert_eq!(
            ClientMetadata::from_value(json!({"user": {"prompt": excessively_long}})),
            Err(DomainError::MetadataStringTooLong {
                max_bytes: MAX_METADATA_STRING_BYTES
            })
        );

        let mut nested = json!(null);
        for _ in 0..=MAX_METADATA_DEPTH {
            nested = json!([nested]);
        }
        assert_eq!(
            ClientMetadata::from_value(json!({"user": {"nested": nested}})),
            Err(DomainError::MetadataTooDeep {
                max_depth: MAX_METADATA_DEPTH
            })
        );
    }
}
