use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

use crate::{
    ApplicationId, BucketId, ClientMetadata, DomainError, DomainResult, MediaId, UploadSessionId,
    Visibility, bucket::canonical_mime_type,
};

/// Durable lifecycle states for a backend-neutral direct upload session.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum UploadSessionState {
    Pending,
    Completed,
    Cancelled,
    Expired,
}

impl UploadSessionState {
    #[must_use]
    pub const fn is_terminal(self) -> bool {
        !matches!(self, Self::Pending)
    }
}

/// Result of applying a terminal action to an upload session.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum UploadSessionTransition {
    Applied,
    AlreadyApplied,
}

/// Server-side input used to create a pending upload session. The target
/// storage location is generated by an adapter before the session is made
/// durable; clients never choose it.
#[derive(Clone, Debug)]
pub struct NewUploadSession {
    pub id: UploadSessionId,
    pub media_id: MediaId,
    pub application_id: ApplicationId,
    pub bucket_id: BucketId,
    pub object_key: String,
    pub original_name: Option<String>,
    pub display_name: String,
    pub extension: Option<String>,
    pub expected_size: u64,
    pub expected_mime: String,
    pub storage_backend: String,
    pub storage_key: String,
    pub visibility_override: Option<Visibility>,
    pub media_expires_at: Option<OffsetDateTime>,
    pub client_metadata: ClientMetadata,
    pub session_expires_at: OffsetDateTime,
}

/// Persistence DTO for an upload session. Rehydrate it through
/// [`UploadSession::from_persistence`] so terminal-state invariants remain in
/// the domain layer.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct PersistedUploadSession {
    pub id: UploadSessionId,
    pub media_id: MediaId,
    pub application_id: ApplicationId,
    pub bucket_id: BucketId,
    pub object_key: String,
    pub original_name: Option<String>,
    pub display_name: String,
    pub extension: Option<String>,
    pub expected_size: u64,
    pub expected_mime: String,
    pub storage_backend: String,
    pub storage_key: String,
    pub visibility_override: Option<Visibility>,
    pub media_expires_at: Option<OffsetDateTime>,
    pub client_metadata: ClientMetadata,
    pub session_expires_at: OffsetDateTime,
    pub state: UploadSessionState,
    pub completed_at: Option<OffsetDateTime>,
    pub cancelled_at: Option<OffsetDateTime>,
    pub expired_at: Option<OffsetDateTime>,
    pub created_at: OffsetDateTime,
    pub updated_at: OffsetDateTime,
}

/// A reserved direct-upload intent. A pending session reserves exactly its
/// expected size; persistence adapters transfer that reservation to used quota
/// on completion or release it atomically on cancellation and expiry.
#[derive(Clone, Debug, PartialEq, Serialize)]
pub struct UploadSession {
    id: UploadSessionId,
    media_id: MediaId,
    application_id: ApplicationId,
    bucket_id: BucketId,
    object_key: String,
    original_name: Option<String>,
    display_name: String,
    extension: Option<String>,
    expected_size: u64,
    expected_mime: String,
    storage_backend: String,
    storage_key: String,
    visibility_override: Option<Visibility>,
    media_expires_at: Option<OffsetDateTime>,
    client_metadata: ClientMetadata,
    session_expires_at: OffsetDateTime,
    state: UploadSessionState,
    completed_at: Option<OffsetDateTime>,
    cancelled_at: Option<OffsetDateTime>,
    expired_at: Option<OffsetDateTime>,
    created_at: OffsetDateTime,
    updated_at: OffsetDateTime,
}

impl UploadSession {
    pub fn new(input: NewUploadSession, now: OffsetDateTime) -> DomainResult<Self> {
        validate_fields(
            &input.object_key,
            input.original_name.as_deref(),
            &input.display_name,
            input.extension.as_deref(),
            &input.storage_backend,
            &input.storage_key,
        )?;
        if input.session_expires_at <= now {
            return Err(DomainError::InvalidUploadSessionExpiry);
        }

        Ok(Self {
            id: input.id,
            media_id: input.media_id,
            application_id: input.application_id,
            bucket_id: input.bucket_id,
            object_key: input.object_key,
            original_name: input.original_name,
            display_name: input.display_name,
            extension: input.extension,
            expected_size: input.expected_size,
            expected_mime: canonical_mime_type(&input.expected_mime)?,
            storage_backend: input.storage_backend,
            storage_key: input.storage_key,
            visibility_override: input.visibility_override,
            media_expires_at: input.media_expires_at,
            client_metadata: input.client_metadata,
            session_expires_at: input.session_expires_at,
            state: UploadSessionState::Pending,
            completed_at: None,
            cancelled_at: None,
            expired_at: None,
            created_at: now,
            updated_at: now,
        })
    }

    pub fn from_persistence(persisted: PersistedUploadSession) -> DomainResult<Self> {
        validate_fields(
            &persisted.object_key,
            persisted.original_name.as_deref(),
            &persisted.display_name,
            persisted.extension.as_deref(),
            &persisted.storage_backend,
            &persisted.storage_key,
        )?;
        validate_terminal_timestamps(
            persisted.state,
            persisted.completed_at,
            persisted.cancelled_at,
            persisted.expired_at,
        )?;

        Ok(Self {
            id: persisted.id,
            media_id: persisted.media_id,
            application_id: persisted.application_id,
            bucket_id: persisted.bucket_id,
            object_key: persisted.object_key,
            original_name: persisted.original_name,
            display_name: persisted.display_name,
            extension: persisted.extension,
            expected_size: persisted.expected_size,
            expected_mime: canonical_mime_type(&persisted.expected_mime)?,
            storage_backend: persisted.storage_backend,
            storage_key: persisted.storage_key,
            visibility_override: persisted.visibility_override,
            media_expires_at: persisted.media_expires_at,
            client_metadata: persisted.client_metadata,
            session_expires_at: persisted.session_expires_at,
            state: persisted.state,
            completed_at: persisted.completed_at,
            cancelled_at: persisted.cancelled_at,
            expired_at: persisted.expired_at,
            created_at: persisted.created_at,
            updated_at: persisted.updated_at,
        })
    }

    #[must_use]
    pub fn to_persisted(&self) -> PersistedUploadSession {
        PersistedUploadSession {
            id: self.id,
            media_id: self.media_id,
            application_id: self.application_id,
            bucket_id: self.bucket_id,
            object_key: self.object_key.clone(),
            original_name: self.original_name.clone(),
            display_name: self.display_name.clone(),
            extension: self.extension.clone(),
            expected_size: self.expected_size,
            expected_mime: self.expected_mime.clone(),
            storage_backend: self.storage_backend.clone(),
            storage_key: self.storage_key.clone(),
            visibility_override: self.visibility_override,
            media_expires_at: self.media_expires_at,
            client_metadata: self.client_metadata.clone(),
            session_expires_at: self.session_expires_at,
            state: self.state,
            completed_at: self.completed_at,
            cancelled_at: self.cancelled_at,
            expired_at: self.expired_at,
            created_at: self.created_at,
            updated_at: self.updated_at,
        }
    }

    #[must_use]
    pub const fn id(&self) -> UploadSessionId {
        self.id
    }

    #[must_use]
    pub const fn media_id(&self) -> MediaId {
        self.media_id
    }

    #[must_use]
    pub const fn application_id(&self) -> ApplicationId {
        self.application_id
    }

    #[must_use]
    pub const fn bucket_id(&self) -> BucketId {
        self.bucket_id
    }

    #[must_use]
    pub fn object_key(&self) -> &str {
        &self.object_key
    }

    #[must_use]
    pub fn original_name(&self) -> Option<&str> {
        self.original_name.as_deref()
    }

    #[must_use]
    pub fn display_name(&self) -> &str {
        &self.display_name
    }

    #[must_use]
    pub fn extension(&self) -> Option<&str> {
        self.extension.as_deref()
    }

    #[must_use]
    pub const fn expected_size(&self) -> u64 {
        self.expected_size
    }

    #[must_use]
    pub fn expected_mime(&self) -> &str {
        &self.expected_mime
    }

    #[must_use]
    pub fn storage_backend(&self) -> &str {
        &self.storage_backend
    }

    #[must_use]
    pub fn storage_key(&self) -> &str {
        &self.storage_key
    }

    #[must_use]
    pub const fn visibility_override(&self) -> Option<Visibility> {
        self.visibility_override
    }

    #[must_use]
    pub const fn media_expires_at(&self) -> Option<OffsetDateTime> {
        self.media_expires_at
    }

    #[must_use]
    pub const fn client_metadata(&self) -> &ClientMetadata {
        &self.client_metadata
    }

    #[must_use]
    pub const fn session_expires_at(&self) -> OffsetDateTime {
        self.session_expires_at
    }

    #[must_use]
    pub const fn state(&self) -> UploadSessionState {
        self.state
    }

    #[must_use]
    pub const fn completed_at(&self) -> Option<OffsetDateTime> {
        self.completed_at
    }

    #[must_use]
    pub const fn cancelled_at(&self) -> Option<OffsetDateTime> {
        self.cancelled_at
    }

    #[must_use]
    pub const fn expired_at(&self) -> Option<OffsetDateTime> {
        self.expired_at
    }

    #[must_use]
    pub const fn created_at(&self) -> OffsetDateTime {
        self.created_at
    }

    #[must_use]
    pub const fn updated_at(&self) -> OffsetDateTime {
        self.updated_at
    }

    /// The pending reservation always equals the requested object size.
    #[must_use]
    pub const fn reserved_bytes(&self) -> u64 {
        self.expected_size
    }

    #[must_use]
    pub fn is_expired_at(&self, now: OffsetDateTime) -> bool {
        self.state == UploadSessionState::Pending && now >= self.session_expires_at
    }

    pub fn complete(&mut self, now: OffsetDateTime) -> DomainResult<UploadSessionTransition> {
        if self.is_expired_at(now) {
            return Err(DomainError::UploadSessionExpired);
        }
        self.apply_terminal_state(UploadSessionState::Completed, now)
    }

    pub fn cancel(&mut self, now: OffsetDateTime) -> DomainResult<UploadSessionTransition> {
        self.apply_terminal_state(UploadSessionState::Cancelled, now)
    }

    pub fn expire(&mut self, now: OffsetDateTime) -> DomainResult<UploadSessionTransition> {
        if self.state == UploadSessionState::Pending && now < self.session_expires_at {
            return Err(DomainError::UploadSessionNotExpired);
        }
        self.apply_terminal_state(UploadSessionState::Expired, now)
    }

    fn apply_terminal_state(
        &mut self,
        next: UploadSessionState,
        now: OffsetDateTime,
    ) -> DomainResult<UploadSessionTransition> {
        if self.state == next {
            return Ok(UploadSessionTransition::AlreadyApplied);
        }
        if self.state != UploadSessionState::Pending {
            return Err(DomainError::InvalidUploadSessionStateTransition {
                from: self.state,
                to: next,
            });
        }

        self.state = next;
        match next {
            UploadSessionState::Completed => self.completed_at = Some(now),
            UploadSessionState::Cancelled => self.cancelled_at = Some(now),
            UploadSessionState::Expired => self.expired_at = Some(now),
            UploadSessionState::Pending => unreachable!("only terminal states are applied"),
        }
        self.updated_at = now;
        Ok(UploadSessionTransition::Applied)
    }
}

fn validate_fields(
    object_key: &str,
    original_name: Option<&str>,
    display_name: &str,
    extension: Option<&str>,
    storage_backend: &str,
    storage_key: &str,
) -> DomainResult<()> {
    if object_key.is_empty() || object_key.len() > 1024 || object_key.as_bytes().contains(&0) {
        return Err(DomainError::InvalidObjectKey);
    }
    validate_text_field("display name", display_name, 255)?;
    if let Some(original_name) = original_name {
        validate_text_field("original name", original_name, 255)?;
    }
    if let Some(extension) = extension {
        validate_text_field("extension", extension, 32)?;
    }
    validate_text_field("storage backend", storage_backend, 128)?;
    validate_text_field("storage key", storage_key, 1024)
}

fn validate_text_field(field: &'static str, value: &str, max_bytes: usize) -> DomainResult<()> {
    if value.is_empty()
        || value.len() > max_bytes
        || value.bytes().any(|byte| byte.is_ascii_control())
    {
        return Err(DomainError::InvalidTextField { field, max_bytes });
    }
    Ok(())
}

fn validate_terminal_timestamps(
    state: UploadSessionState,
    completed_at: Option<OffsetDateTime>,
    cancelled_at: Option<OffsetDateTime>,
    expired_at: Option<OffsetDateTime>,
) -> DomainResult<()> {
    let valid = match state {
        UploadSessionState::Pending => {
            completed_at.is_none() && cancelled_at.is_none() && expired_at.is_none()
        }
        UploadSessionState::Completed => {
            completed_at.is_some() && cancelled_at.is_none() && expired_at.is_none()
        }
        UploadSessionState::Cancelled => {
            completed_at.is_none() && cancelled_at.is_some() && expired_at.is_none()
        }
        UploadSessionState::Expired => {
            completed_at.is_none() && cancelled_at.is_none() && expired_at.is_some()
        }
    };
    if valid {
        Ok(())
    } else {
        Err(DomainError::InvalidUploadSessionStateTransition {
            from: state,
            to: state,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn new_session(now: OffsetDateTime) -> UploadSession {
        UploadSession::new(
            NewUploadSession {
                id: UploadSessionId::new(),
                media_id: MediaId::new(),
                application_id: ApplicationId::new(),
                bucket_id: BucketId::new(),
                object_key: "avatars/example.png".to_owned(),
                original_name: Some("example.png".to_owned()),
                display_name: "Example".to_owned(),
                extension: Some("png".to_owned()),
                expected_size: 42,
                expected_mime: "IMAGE/PNG".to_owned(),
                storage_backend: "s3".to_owned(),
                storage_key: "uploads/example".to_owned(),
                visibility_override: None,
                media_expires_at: None,
                client_metadata: ClientMetadata::default(),
                session_expires_at: now + time::Duration::minutes(15),
            },
            now,
        )
        .expect("valid upload session")
    }

    #[test]
    fn completion_is_idempotent_and_preserves_its_timestamp() {
        let now = OffsetDateTime::UNIX_EPOCH;
        let mut session = new_session(now);

        assert_eq!(
            session.complete(now + time::Duration::seconds(1)),
            Ok(UploadSessionTransition::Applied)
        );
        let completed_at = session.completed_at();
        assert_eq!(
            session.complete(now + time::Duration::seconds(2)),
            Ok(UploadSessionTransition::AlreadyApplied)
        );
        assert_eq!(session.completed_at(), completed_at);
        assert!(matches!(
            session.cancel(now + time::Duration::seconds(3)),
            Err(DomainError::InvalidUploadSessionStateTransition { .. })
        ));
    }

    #[test]
    fn cancellation_and_expiry_are_idempotent_without_crossing_terminal_states() {
        let now = OffsetDateTime::UNIX_EPOCH;
        let mut cancelled = new_session(now);
        assert_eq!(cancelled.cancel(now), Ok(UploadSessionTransition::Applied));
        assert_eq!(
            cancelled.cancel(now + time::Duration::seconds(1)),
            Ok(UploadSessionTransition::AlreadyApplied)
        );

        let mut expired = new_session(now);
        let expires_at = expired.session_expires_at();
        assert_eq!(
            expired.expire(expires_at),
            Ok(UploadSessionTransition::Applied)
        );
        assert_eq!(
            expired.expire(expires_at + time::Duration::seconds(1)),
            Ok(UploadSessionTransition::AlreadyApplied)
        );
        assert!(matches!(
            expired.complete(expires_at + time::Duration::seconds(2)),
            Err(DomainError::InvalidUploadSessionStateTransition { .. })
        ));
    }

    #[test]
    fn pending_session_cannot_complete_after_expiry() {
        let now = OffsetDateTime::UNIX_EPOCH;
        let mut session = new_session(now);
        assert_eq!(
            session.complete(session.session_expires_at()),
            Err(DomainError::UploadSessionExpired)
        );
        assert_eq!(session.state(), UploadSessionState::Pending);
    }
}
